### ISSUE TITLE
Security vulnerability in node-forge

### ISSUE THREAD

**Issue by alex-friedl** [parse-community/node-apn#103]
Hello,

one of our users reported that your version of `node-forge` has some security issues (https://github.com/appfeel/node-pushnotifications/issues/172)

This is the relevant Github security advisory: https://github.com/advisories/GHSA-2r2c-g63r-vccr 

Could you look into updating the dependency on your end? 

Thank you!

Best regards
Alex

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/node-apn/pull/101
