### ISSUE TITLE
shutdown callback is not passed through from the Provider to the Client

### ISSUE THREAD

**Issue by pigulla** [parse-community/node-apn#117]
When `Provider.shutdown()` is called with a callback, that callback is not passed through to the client.

See the [source](https://github.com/parse-community/node-apn/blob/650993dcfc210485def7b4ce6ddf68e6c6a32878/lib/provider.js#L45):
```javascript
Provider.prototype.shutdown = function shutdown() {
  this.client.shutdown();
};
```

This is contrary to what is specified in the [TypeScript definition](https://github.com/parse-community/node-apn/blob/master/index.d.ts#L141).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.2](https://github.com/parse-community/node-apn/releases/tag/5.2.2)
