### ISSUE TITLE
Add support for Node 18, 20

### ISSUE THREAD

**Issue by mtrezza** [parse-community/node-apn#132]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/node-apn/releases/tag/6.0.0)

**Comment by ivandotv** [comment]
Do we need to do anything special for Node `v21`, or this change is future proof?

**Comment by Tim4497** [comment]
> Do we need to do anything special for Node `v21`, or this change is future proof?

Or v22? As I am getting `Error: Unsupported PKCS12 PFX data` at the moment.

**Comment by mtrezza** [comment]
> PKCS12 PFX data

Sounds more like certificate related? Newer Node versions sometimes remove default support for insecure certificate algorithms.
