### ISSUE TITLE
Uncaught VError: Failed to generate token: secretOrPrivateKey must be an asymmetric key when using ES256

### ISSUE THREAD

**Issue by tkafka** [parse-community/node-apn#134]
Hello, I have generated the token for push notifications at Keys section (https://developer.apple.com/account/resources/authkeys/list), enabled `Apple Push Notifications service (APNs)` there, but when using the generated key (`AuthKey_XXXYYYZZZ.p8`), I get an error `Uncaught VError: Failed to generate token: secretOrPrivateKey must be an asymmetric key when using ES256` from `lib/credentials/token/prepare.js:41:13`.

I have found that the cause probably is that Apple's generated key is a symmetrical one. Is there a way to convert it to an asymmetrical one, or generate the one that will be accepted?

**Comment by innesngunn** [comment]
I see this issue is closed but I am getting the same error as @tkafka. Any fix or workaround?

**Comment by innesngunn** [comment]
I deleted my node_modules folder and reinstalled from npm. No errors anymore.
