### ISSUE TITLE
Live Activity app not producing proper APS payload (events instead of event, missing dismissal-date)

### ISSUE THREAD

**Issue by kurtguenther** [parse-community/node-apn#135]
[Since 5.2.3](https://github.com/parse-community/node-apn/pull/133#issuecomment-1747747998), node-apn has been producing slightly wrong APS payloads, renaming `events` instead of `event` in the live activity push notifications.

Additionally, there wasn't any support for `dismissal-date` which is used when the `event` type is `end`.

cc: @dplewis

**Comment by cbaker6** [comment]
@mtrezza this can be closed as it was addressed in #148
