### ISSUE TITLE
I miss the localised subtitle properties `subtitle-loc-key` and `subtitle-loc-args` because you're using old Apple documentation

### ISSUE THREAD

**Issue by funnel20** [parse-community/node-apn#139]
Thanks for this great lib.

The detailed `apn.Notification` [documentation](https://github.com/parse-community/node-apn/blob/4cf2c03dc749312464f192f83d932c9b2aa0dd25/doc/notification.markdown#class-apnnotification) refers to the Apple payload documentation at https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html

This link is outdated, the modern docu can be found at https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification
In particular Table 2 is important, as it shows a set of new keys which is not present in your [Convenience Setters](https://github.com/parse-community/node-apn/blob/4cf2c03dc749312464f192f83d932c9b2aa0dd25/doc/notification.markdown#convenience-setters).
Among them the subtitle and it's localised variants; `subtitle-loc-key` and `subtitle-loc-args`.

Would it be possible to add these and other missing ones and update your documentation?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.2.0](https://github.com/parse-community/node-apn/releases/tag/6.2.0)

**Comment by mtrezza** [comment]
(Forwarding your thanks to @cbaker who provided the PR)

**Comment by funnel20** [comment]
Version 6.2.0 successful in production after using the 2 new fields ✅
Here is the server log:

```
Sending 11 notifications...
 · Completed sending 11 notifications in 0.66 seconds (17 messages/second)
 · 11 sent, 0 failed
```
