### ISSUE TITLE
Add ability to add dismissal date to Live Activity push notification

### ISSUE THREAD

**Issue by cbaker6** [parse-community/node-apn#153]
Live activities currently can't add a custom dismissal date which, `To set a custom dismissal date that tells the system to remove an ended Live Activity from the Lock Screen`

Reference: https://developer.apple.com/documentation/activitykit/starting-and-updating-live-activities-with-activitykit-push-notifications

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0](https://github.com/parse-community/node-apn/releases/tag/6.1.0)
