### ISSUE TITLE
Certificate Authority (CA) for Apple Push Notification (APN) is changing

### ISSUE THREAD

**Issue by bill-foreflight** [parse-community/node-apn#161]
I wasn't sure where to post this - but was trying to figure out if uses of this library need to take any action in response to Apple announcement that APNs will update the server certificates in early 2025?

https://developer.apple.com/news/?id=09za8wzy

**Comment by junjie** [comment]
Thanks for opening this issue. I'm wondering about it too.

**Comment by mtrezza** [comment]
I don't think we hardcode any cert trust stores here.

**Comment by junjie** [comment]
Thanks for taking time to explain the situation @mtrezza!

**Comment by llee1990** [comment]
@mtrezza 

![image](https://github.com/user-attachments/assets/835d93bb-41f2-4a9a-90cb-82b69cdafd90)

It says in the docs that `If this is omitted several well known "root" CAs will be used`, would you happen to know if these default CAs includes `SHA-2 Root : USERTrust RSA Certification Authority`?

Thanks!

**Comment by junjie** [comment]
FYI, I have tested node-apn following the update to the server certificates in sandbox on January 20, 2025, and everything works as before.

**Comment by llee1990** [comment]
It is working for me as well 🙂
