### ISSUE TITLE
Broadcast push notifications

### ISSUE THREAD

**Issue by IsaiahJTurner** [parse-community/node-apn#162]
Are there any plans to support broadcast push notifications for Live Activities?

https://developer.apple.com/documentation/UserNotifications/sending-broadcast-push-notification-requests-to-apns

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/node-apn/releases/tag/6.3.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/node-apn/releases/tag/6.4.0)
