### ISSUE TITLE
Idea: support connection pooling where apn.Provider has a configurable number of 1+ clients

### ISSUE THREAD

**Issue by TysonAndre** [parse-community/node-apn#34]
http2.connect creates a single encrypted TCP socket. This may have limited bandwidth if there is a bottleneck in APNs, or may be more prone to some requests (99.99% percentile) taking much longer than others (e.g. 5+ seconds). If there is a dropped packet, more data would need to be retransmitted.

- Investigate if this is actually a bottleneck in applications using node-apn. Apple's documentation mentions there shouldn't be any deliberate caps
- Other http2 clients such as https://godoc.org/golang.org/x/net/http2 maintains a connection pool internally
- This could help avoid interruptions if the provider prefers clients which are connected over clients that are actively reconnecting - I haven't seen disconnections in practice, though

**Comment by TysonAndre** [comment]
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/ mentions the following for Best Practices While Connecting to APNs

> - Depending on throughput and request-response turnaround time, open new connections.
> - Avoid push burst over selective connections. Diversifying push traffic over many connections distributes push traffic for your application across all APNs servers.

**Comment by eladnava** [comment]
That's awesome.

For the time being (until this is merged), I am replicating this behavior by creating multiple `apn.Provider` instances and iterating them in a round-robin style:

```
// Create a pool of providers (multiple connections)
var apnsProviders = [], providerCount = 50, currentProvider = 0;

// Create providers
for (var i = 0; i < providerCount; i++) {
    // Set up apn with the APNs Auth Key
    apnsProviders.push(new apn.Provider({
        token: config.apns,
        production: process.platform == 'darwin'
    }));
}
```

And in the notification sending section:
```
    // Actually send the notification
    apnsProviders[currentProvider].send(notification, token).then((result) => {
        // console.log(result);
        if (doneCallback) {
            doneCallback();
        }
    })

    // Increment provider
    currentProvider++;

    // End of the provider list?
    if (currentProvider >= apnsProviders.length) {
        currentProvider = 0;
    }
```
