### ISSUE TITLE
Make topic not required

### ISSUE THREAD

**Issue by alexibz** [parse-community/node-apn#41]
Currently the docs state that a `topic` must be specified for a notification, but this isn't always the case. From the apple docs:

_If you omit this request header and your APNs certificate does not specify multiple topics, the APNs server uses the certificate’s Subject as the default topic._

**Comment by davimacedo** [comment]
Thanks for reporting. Would you be willed to open a PR?

**Comment by alexibz** [comment]
I've tried to create a payload _without_ the topic in the header but kept receiving the `MissingTopic` error even though Im using a p12 certificate with only one possible bundleId. I think the apple docs might not be updated. I've checked other  libraries [implementing apns ](https://awesomeopensource.com/projects/apns) and they all state that `topic` is required. Closing my issue in this case.
