### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by forty** [parse-community/node-apn#48]
The original node-apn had support for HTTP proxy. This feature was apparently lost with the migration to native HTTP2 module (even if it's this mentioned in the README). It would be great if it could be added again.

**Comment by cakenyo** [comment]
Any update about this? using node-apn with proxy, and can't really move to this fork cuz of that.

**Comment by kinolaev** [comment]
Hello! See PR #62

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/node-apn/pull/62
