### ISSUE TITLE
Updated APNs provider API deadline

### ISSUE THREAD

**Issue by chishih** [parse-community/node-apn#54]
The HTTP/2-based Apple Push Notification service (APNs) provider API lets you take advantage of great features, such as authentication with a JSON Web Token, improved error messaging, and per-notification feedback. If you send push notifications with the legacy binary protocol, we strongly recommend upgrading to the APNs provider API.

To give you additional time to prepare, the deadline to upgrade to the APNs provider API has been extended to March 31, 2021. APNs will no longer support the legacy binary protocol after this date.

Does it have any impact on the node-apn package?

**Comment by davimacedo** [comment]
The latest version of this package already uses HTTP/2.
