### ISSUE TITLE
Idea: Add support to zero-valued (0) `expiry`

### ISSUE THREAD

**Issue by b-marques** [parse-community/node-apn#57]
It was done in official node-apn. It would be nice to also apply here.

https://github.com/node-apn/node-apn/commit/ac0e163f698fb9a198ca36009755145a7171be57#diff-97dd2011fdf4204ec3cc04e1adf3de602f18e6e901ccf32330bdf2ff7f9bf8e7

**Comment by davimacedo** [comment]
It looks a good addition. Would you be willed to open a PR here?

**Comment by b-marques** [comment]
Already done. 

https://github.com/parse-community/node-apn/pull/58
