### ISSUE TITLE
IOS devices stop receiving the Push notifications

### ISSUE THREAD

**Issue by samulla** [parse-community/node-apn#61]
Dear folks,
From March 15th, all iOS devices using our App have stopped receiving push notifications. When I checked the server logs, I see the below set of errors

1. apn Session error: Error: unable to get local issuer certificate.
2. apn Request error: Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: unable to get local issuer certificate)
3. apn Request ended with status null and responseData:
4. ErrorWithStatus: stream ended unexpectedly\n at /home/vcap/app/node_modules/node-push/middleware/proxyPushNotification.js:23:10\n at process._tickCallback

Any idea or help?

Best Regards,
Sami

**Comment by davimacedo** [comment]
it looks you are using a module called `node-push` and not `node-apn`

**Comment by mtrezza** [comment]
I'm closing this as it seems to relate to another package. Feel free to comment if you have any questions and we can re-open this issue.
