### ISSUE TITLE
Publish a new 4.x release?

### ISSUE THREAD

**Issue by TysonAndre** [parse-community/node-apn#69]
Related to #67 

This contains some useful features in https://github.com/parse-community/node-apn/compare/4.0.0...master

**Comment by davimacedo** [comment]
Do you want to wait for the multiclient PR? Otherwise I believe we can release a new version right away.

**Comment by TysonAndre** [comment]
> Do you want to wait for the multiclient PR? Otherwise I believe we can release a new version right away.

You can release a new version right away - multiclient can wait and I don't think it'll work in node prior to node 12, for an unknown reason.

**Comment by davimacedo** [comment]
I've just created the PR: https://github.com/parse-community/node-apn/pull/70
