### ISSUE TITLE
Publish a new 5.0.0 release?

### ISSUE THREAD

**Issue by TysonAndre** [parse-community/node-apn#79]
https://github.com/parse-community/node-apn/pull/66 was merged a while ago but no release was created.

.github/workflows/release.yml is using node 10.14, and the minimum node version package.json is 12, but it seems unrelated - instead, the issue is just that no GitHub release is created?

Are there any other planned changes for the major release?

**Comment by davimacedo** [comment]
We need to create a release and we should go for it. There aren't other planned changes.

I will fix the CI node version and then we can release.

BTW, would you be interested in joining in the maintainers team for this project?

**Comment by davimacedo** [comment]
That's cool. 5.0.0 was just released. About joining the team, I've just posted a voting on our forum (https://community.parseplatform.org/t/vote-to-add-tysonandre-as-a-member/1881), according to our governance, and should be able to give you access next week.

**Comment by davimacedo** [comment]
@TysonAndre just sent you an invite to the team. Welcome! Please let me know in the case you have any question.
