### ISSUE TITLE
aps property on Notification is being set to undefined

### ISSUE THREAD

**Issue by scottwestover** [parse-community/node-apn#99]
I am not sure if this is intended behavior, or a bug, but I started running into an issue that was similar to the issue reported here: https://github.com/parse-community/node-apn/issues/59#issuecomment-804683312.

Basically, when I create a notification like so:
```
let notification = new apn.Notification();
notification.payload = {
    aps: data
};
```

I am able to send that notification and I get a success response like so:
```
{"sent":[{"device":"test_device_id"}],"failed":[]}
```

However, the notification never shows up on my device.

If I manually set the `aps` property, the notification will show up on the device:
```
let notification = new apn.Notification();
notification.payload = {
    aps: data
};
notification.aps = data;
```

In the code: https://github.com/parse-community/node-apn/blob/master/lib/notification/index.js#L127, it looks like if the `aps` property is never set, the code is setting `payload.aps` to `undefined`. There is also a unit test to make sure the `aps` property is not present when the field is on the original `payload` object: https://github.com/parse-community/node-apn/blob/master/test/notification/index.js#L99.

In the documentation: https://github.com/parse-community/node-apn/blob/master/doc/notification.markdown#payload, the docs only mention that the `aps` property will be overridden on the `payload` object if `aps` was set on the object.

Is this the correct intended behavior? If so, can you please share why?

**Comment by davimacedo** [comment]
I am not sure about the reason, but it is the intended behavior from what I understood looking at the code and docs. aps needs to be set in the notification object and not in the payload. Anything set in the payload will be replaced, even to undefined.

**Comment by scottwestover** [comment]
@davimacedo Thanks for the quick response and confirming that this is intended behavior. I will make sure to use the `aps` property and appropriate methods directly.
